// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27jK9mhrCe1Y_um9Tr0iw3Rt9cbzpgdY',
    appId: '1:98584794528:web:c0df0f22bdc88ca3c280c5',
    messagingSenderId: '98584794528',
    projectId: 'ipssien2023',
    authDomain: 'ipssien2023.firebaseapp.com',
    storageBucket: 'ipssien2023.appspot.com',
    measurementId: 'G-LQERYNPXCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ9O9YCmWDeI3y_pYLuTSh-tmSk9hFxxI',
    appId: '1:98584794528:android:ec036cd1f5066a58c280c5',
    messagingSenderId: '98584794528',
    projectId: 'ipssien2023',
    storageBucket: 'ipssien2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9DiwMGkv_YYegYpf2OqTkgrgDUFENRyI',
    appId: '1:98584794528:ios:d2a8c7f03a05e9e6c280c5',
    messagingSenderId: '98584794528',
    projectId: 'ipssien2023',
    storageBucket: 'ipssien2023.appspot.com',
    iosClientId: '98584794528-8aqn9ci9dh28tcamqc5961mugvf097so.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipssi2023montevrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9DiwMGkv_YYegYpf2OqTkgrgDUFENRyI',
    appId: '1:98584794528:ios:d2a8c7f03a05e9e6c280c5',
    messagingSenderId: '98584794528',
    projectId: 'ipssien2023',
    storageBucket: 'ipssien2023.appspot.com',
    iosClientId: '98584794528-8aqn9ci9dh28tcamqc5961mugvf097so.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipssi2023montevrain',
  );
}
